	Exporter version: 4.5.0, Blender version: 2.76 (sub 0)
========= Conversion from Blender to Babylon.js =========
	Scene settings used:
		selected layers only:  false
		flat shading entire scene:  false
		inline textures:  false
		texture directory:  E:\Dropbox\Babylonjs Game\meteorgame\public\assets\
	Python World class constructor completed
	processing begun of mesh:  Cube.009
		processing begun of Standard material:  Material.005
		num positions      :  655
		num normals        :  655
		num uvs            :  1310
		num uvs2           :  0
		num colors         :  0
		num indices        :  3720
	processing begun of mesh:  Cube.001
		registered as also a user of material:  Material.005
		num positions      :  655
		num normals        :  655
		num uvs            :  1310
		num uvs2           :  0
		num colors         :  0
		num indices        :  3720
	processing begun of mesh:  head.000
		processing begun of baked material:  head.000
			Internal baking texture, type: ALPHA, mapped using: BakingUV
========= An error was encountered =========
  File "C:\Users\Hampus\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\io_export_babylon.py", line 329, in execute
    mesh = Mesh(object, scene, nextStartFace, forcedParent, nameID, self)
  File "C:\Users\Hampus\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\io_export_babylon.py", line 785, in __init__
    bakedMat = BakedMaterial(exporter, object, recipe)
  File "C:\Users\Hampus\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\io_export_babylon.py", line 2138, in __init__
    self.bake('opacityTexture', None, 'ALPHA', image, mesh, uvName, exporter, recipe)
  File "C:\Users\Hampus\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\io_export_babylon.py", line 2166, in bake
    self.bakeInternal(internal_type, image, uvName)
  File "C:\Users\Hampus\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\io_export_babylon.py", line 2195, in bakeInternal
    bpy.ops.object.bake_image()
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
ERROR:  Error: No valid images found to bake to

========= end of processing =========
elapsed time:  0 min, 0.1715 secs
